// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: ingestion.proto

package ingestionpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_STATUS_UNSPECIFIED      Status = 0
	Status_STATUS_OK               Status = 1
	Status_STATUS_VALIDATION_ERROR Status = 2
	Status_STATUS_DUPLICATE        Status = 3
	Status_STATUS_RATE_LIMITED     Status = 4
	Status_STATUS_INTERNAL_ERROR   Status = 5
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_OK",
		2: "STATUS_VALIDATION_ERROR",
		3: "STATUS_DUPLICATE",
		4: "STATUS_RATE_LIMITED",
		5: "STATUS_INTERNAL_ERROR",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED":      0,
		"STATUS_OK":               1,
		"STATUS_VALIDATION_ERROR": 2,
		"STATUS_DUPLICATE":        3,
		"STATUS_RATE_LIMITED":     4,
		"STATUS_INTERNAL_ERROR":   5,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_ingestion_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_ingestion_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_ingestion_proto_rawDescGZIP(), []int{0}
}

type SourceFormat int32

const (
	SourceFormat_FORMAT_UNSPECIFIED SourceFormat = 0
	SourceFormat_FORMAT_JSON_LINES  SourceFormat = 1
	SourceFormat_FORMAT_PARQUET     SourceFormat = 2
	SourceFormat_FORMAT_CSV         SourceFormat = 3
)

// Enum value maps for SourceFormat.
var (
	SourceFormat_name = map[int32]string{
		0: "FORMAT_UNSPECIFIED",
		1: "FORMAT_JSON_LINES",
		2: "FORMAT_PARQUET",
		3: "FORMAT_CSV",
	}
	SourceFormat_value = map[string]int32{
		"FORMAT_UNSPECIFIED": 0,
		"FORMAT_JSON_LINES":  1,
		"FORMAT_PARQUET":     2,
		"FORMAT_CSV":         3,
	}
)

func (x SourceFormat) Enum() *SourceFormat {
	p := new(SourceFormat)
	*p = x
	return p
}

func (x SourceFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SourceFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_ingestion_proto_enumTypes[1].Descriptor()
}

func (SourceFormat) Type() protoreflect.EnumType {
	return &file_ingestion_proto_enumTypes[1]
}

func (x SourceFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SourceFormat.Descriptor instead.
func (SourceFormat) EnumDescriptor() ([]byte, []int) {
	return file_ingestion_proto_rawDescGZIP(), []int{1}
}

type JobStatus int32

const (
	JobStatus_JOB_STATUS_UNSPECIFIED JobStatus = 0
	JobStatus_JOB_STATUS_PENDING     JobStatus = 1
	JobStatus_JOB_STATUS_RUNNING     JobStatus = 2
	JobStatus_JOB_STATUS_COMPLETED   JobStatus = 3
	JobStatus_JOB_STATUS_FAILED      JobStatus = 4
)

// Enum value maps for JobStatus.
var (
	JobStatus_name = map[int32]string{
		0: "JOB_STATUS_UNSPECIFIED",
		1: "JOB_STATUS_PENDING",
		2: "JOB_STATUS_RUNNING",
		3: "JOB_STATUS_COMPLETED",
		4: "JOB_STATUS_FAILED",
	}
	JobStatus_value = map[string]int32{
		"JOB_STATUS_UNSPECIFIED": 0,
		"JOB_STATUS_PENDING":     1,
		"JOB_STATUS_RUNNING":     2,
		"JOB_STATUS_COMPLETED":   3,
		"JOB_STATUS_FAILED":      4,
	}
)

func (x JobStatus) Enum() *JobStatus {
	p := new(JobStatus)
	*p = x
	return p
}

func (x JobStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_ingestion_proto_enumTypes[2].Descriptor()
}

func (JobStatus) Type() protoreflect.EnumType {
	return &file_ingestion_proto_enumTypes[2]
}

func (x JobStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobStatus.Descriptor instead.
func (JobStatus) EnumDescriptor() ([]byte, []int) {
	return file_ingestion_proto_rawDescGZIP(), []int{2}
}

type IngestRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StreamId       string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	SchemaId       string                 `protobuf:"bytes,2,opt,name=schema_id,json=schemaId,proto3" json:"schema_id,omitempty"`
	Payload        []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`                                                                             // JSON-encoded record
	IdempotencyKey *string                `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3,oneof" json:"idempotency_key,omitempty"`                                   // Client-provided dedup key
	Metadata       map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Custom metadata
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *IngestRequest) Reset() {
	*x = IngestRequest{}
	mi := &file_ingestion_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestRequest) ProtoMessage() {}

func (x *IngestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestRequest.ProtoReflect.Descriptor instead.
func (*IngestRequest) Descriptor() ([]byte, []int) {
	return file_ingestion_proto_rawDescGZIP(), []int{0}
}

func (x *IngestRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *IngestRequest) GetSchemaId() string {
	if x != nil {
		return x.SchemaId
	}
	return ""
}

func (x *IngestRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *IngestRequest) GetIdempotencyKey() string {
	if x != nil && x.IdempotencyKey != nil {
		return *x.IdempotencyKey
	}
	return ""
}

func (x *IngestRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type IngestResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	RecordId            string                 `protobuf:"bytes,1,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`                                     // Server-assigned ID
	SequenceNumber      int64                  `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`                  // Per-stream sequence
	TimestampUnixMicros int64                  `protobuf:"varint,3,opt,name=timestamp_unix_micros,json=timestampUnixMicros,proto3" json:"timestamp_unix_micros,omitempty"` // Server receive time
	Status              Status                 `protobuf:"varint,4,opt,name=status,proto3,enum=ttdust.ingestion.v1.Status" json:"status,omitempty"`
	ErrorMessage        *string                `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *IngestResponse) Reset() {
	*x = IngestResponse{}
	mi := &file_ingestion_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestResponse) ProtoMessage() {}

func (x *IngestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestResponse.ProtoReflect.Descriptor instead.
func (*IngestResponse) Descriptor() ([]byte, []int) {
	return file_ingestion_proto_rawDescGZIP(), []int{1}
}

func (x *IngestResponse) GetRecordId() string {
	if x != nil {
		return x.RecordId
	}
	return ""
}

func (x *IngestResponse) GetSequenceNumber() int64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *IngestResponse) GetTimestampUnixMicros() int64 {
	if x != nil {
		return x.TimestampUnixMicros
	}
	return 0
}

func (x *IngestResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *IngestResponse) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

type IngestBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	SchemaId      string                 `protobuf:"bytes,2,opt,name=schema_id,json=schemaId,proto3" json:"schema_id,omitempty"`
	SourceUri     string                 `protobuf:"bytes,3,opt,name=source_uri,json=sourceUri,proto3" json:"source_uri,omitempty"` // S3 URI to source file
	Format        SourceFormat           `protobuf:"varint,4,opt,name=format,proto3,enum=ttdust.ingestion.v1.SourceFormat" json:"format,omitempty"`
	Options       map[string]string      `protobuf:"bytes,5,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Format-specific options
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestBatchRequest) Reset() {
	*x = IngestBatchRequest{}
	mi := &file_ingestion_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestBatchRequest) ProtoMessage() {}

func (x *IngestBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestBatchRequest.ProtoReflect.Descriptor instead.
func (*IngestBatchRequest) Descriptor() ([]byte, []int) {
	return file_ingestion_proto_rawDescGZIP(), []int{2}
}

func (x *IngestBatchRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *IngestBatchRequest) GetSchemaId() string {
	if x != nil {
		return x.SchemaId
	}
	return ""
}

func (x *IngestBatchRequest) GetSourceUri() string {
	if x != nil {
		return x.SourceUri
	}
	return ""
}

func (x *IngestBatchRequest) GetFormat() SourceFormat {
	if x != nil {
		return x.Format
	}
	return SourceFormat_FORMAT_UNSPECIFIED
}

func (x *IngestBatchRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type IngestBatchResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	JobId            string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status           JobStatus              `protobuf:"varint,2,opt,name=status,proto3,enum=ttdust.ingestion.v1.JobStatus" json:"status,omitempty"`
	RecordsProcessed int64                  `protobuf:"varint,3,opt,name=records_processed,json=recordsProcessed,proto3" json:"records_processed,omitempty"`
	RecordsSucceeded int64                  `protobuf:"varint,4,opt,name=records_succeeded,json=recordsSucceeded,proto3" json:"records_succeeded,omitempty"`
	RecordsFailed    int64                  `protobuf:"varint,5,opt,name=records_failed,json=recordsFailed,proto3" json:"records_failed,omitempty"`
	Errors           []*BatchError          `protobuf:"bytes,6,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *IngestBatchResponse) Reset() {
	*x = IngestBatchResponse{}
	mi := &file_ingestion_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestBatchResponse) ProtoMessage() {}

func (x *IngestBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestBatchResponse.ProtoReflect.Descriptor instead.
func (*IngestBatchResponse) Descriptor() ([]byte, []int) {
	return file_ingestion_proto_rawDescGZIP(), []int{3}
}

func (x *IngestBatchResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *IngestBatchResponse) GetStatus() JobStatus {
	if x != nil {
		return x.Status
	}
	return JobStatus_JOB_STATUS_UNSPECIFIED
}

func (x *IngestBatchResponse) GetRecordsProcessed() int64 {
	if x != nil {
		return x.RecordsProcessed
	}
	return 0
}

func (x *IngestBatchResponse) GetRecordsSucceeded() int64 {
	if x != nil {
		return x.RecordsSucceeded
	}
	return 0
}

func (x *IngestBatchResponse) GetRecordsFailed() int64 {
	if x != nil {
		return x.RecordsFailed
	}
	return 0
}

func (x *IngestBatchResponse) GetErrors() []*BatchError {
	if x != nil {
		return x.Errors
	}
	return nil
}

type BatchError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LineNumber    int64                  `protobuf:"varint,1,opt,name=line_number,json=lineNumber,proto3" json:"line_number,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Field         string                 `protobuf:"bytes,3,opt,name=field,proto3" json:"field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchError) Reset() {
	*x = BatchError{}
	mi := &file_ingestion_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchError) ProtoMessage() {}

func (x *BatchError) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchError.ProtoReflect.Descriptor instead.
func (*BatchError) Descriptor() ([]byte, []int) {
	return file_ingestion_proto_rawDescGZIP(), []int{4}
}

func (x *BatchError) GetLineNumber() int64 {
	if x != nil {
		return x.LineNumber
	}
	return 0
}

func (x *BatchError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BatchError) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

var File_ingestion_proto protoreflect.FileDescriptor

const file_ingestion_proto_rawDesc = "" +
	"\n" +
	"\x0fingestion.proto\x12\x13ttdust.ingestion.v1\"\xb0\x02\n" +
	"\rIngestRequest\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12\x1b\n" +
	"\tschema_id\x18\x02 \x01(\tR\bschemaId\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12,\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tH\x00R\x0eidempotencyKey\x88\x01\x01\x12L\n" +
	"\bmetadata\x18\x05 \x03(\v20.ttdust.ingestion.v1.IngestRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x12\n" +
	"\x10_idempotency_key\"\xfb\x01\n" +
	"\x0eIngestResponse\x12\x1b\n" +
	"\trecord_id\x18\x01 \x01(\tR\brecordId\x12'\n" +
	"\x0fsequence_number\x18\x02 \x01(\x03R\x0esequenceNumber\x122\n" +
	"\x15timestamp_unix_micros\x18\x03 \x01(\x03R\x13timestampUnixMicros\x123\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1b.ttdust.ingestion.v1.StatusR\x06status\x12(\n" +
	"\rerror_message\x18\x05 \x01(\tH\x00R\ferrorMessage\x88\x01\x01B\x10\n" +
	"\x0e_error_message\"\xb4\x02\n" +
	"\x12IngestBatchRequest\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12\x1b\n" +
	"\tschema_id\x18\x02 \x01(\tR\bschemaId\x12\x1d\n" +
	"\n" +
	"source_uri\x18\x03 \x01(\tR\tsourceUri\x129\n" +
	"\x06format\x18\x04 \x01(\x0e2!.ttdust.ingestion.v1.SourceFormatR\x06format\x12N\n" +
	"\aoptions\x18\x05 \x03(\v24.ttdust.ingestion.v1.IngestBatchRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9e\x02\n" +
	"\x13IngestBatchResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x126\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1e.ttdust.ingestion.v1.JobStatusR\x06status\x12+\n" +
	"\x11records_processed\x18\x03 \x01(\x03R\x10recordsProcessed\x12+\n" +
	"\x11records_succeeded\x18\x04 \x01(\x03R\x10recordsSucceeded\x12%\n" +
	"\x0erecords_failed\x18\x05 \x01(\x03R\rrecordsFailed\x127\n" +
	"\x06errors\x18\x06 \x03(\v2\x1f.ttdust.ingestion.v1.BatchErrorR\x06errors\"]\n" +
	"\n" +
	"BatchError\x12\x1f\n" +
	"\vline_number\x18\x01 \x01(\x03R\n" +
	"lineNumber\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05field\x18\x03 \x01(\tR\x05field*\x96\x01\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tSTATUS_OK\x10\x01\x12\x1b\n" +
	"\x17STATUS_VALIDATION_ERROR\x10\x02\x12\x14\n" +
	"\x10STATUS_DUPLICATE\x10\x03\x12\x17\n" +
	"\x13STATUS_RATE_LIMITED\x10\x04\x12\x19\n" +
	"\x15STATUS_INTERNAL_ERROR\x10\x05*a\n" +
	"\fSourceFormat\x12\x16\n" +
	"\x12FORMAT_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11FORMAT_JSON_LINES\x10\x01\x12\x12\n" +
	"\x0eFORMAT_PARQUET\x10\x02\x12\x0e\n" +
	"\n" +
	"FORMAT_CSV\x10\x03*\x88\x01\n" +
	"\tJobStatus\x12\x1a\n" +
	"\x16JOB_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12JOB_STATUS_PENDING\x10\x01\x12\x16\n" +
	"\x12JOB_STATUS_RUNNING\x10\x02\x12\x18\n" +
	"\x14JOB_STATUS_COMPLETED\x10\x03\x12\x15\n" +
	"\x11JOB_STATUS_FAILED\x10\x042\xd1\x01\n" +
	"\x10IngestionService\x12[\n" +
	"\fIngestStream\x12\".ttdust.ingestion.v1.IngestRequest\x1a#.ttdust.ingestion.v1.IngestResponse(\x010\x01\x12`\n" +
	"\vIngestBatch\x12'.ttdust.ingestion.v1.IngestBatchRequest\x1a(.ttdust.ingestion.v1.IngestBatchResponseB(Z&GoTTDust/internal/genproto/ingestionpbb\x06proto3"

var (
	file_ingestion_proto_rawDescOnce sync.Once
	file_ingestion_proto_rawDescData []byte
)

func file_ingestion_proto_rawDescGZIP() []byte {
	file_ingestion_proto_rawDescOnce.Do(func() {
		file_ingestion_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ingestion_proto_rawDesc), len(file_ingestion_proto_rawDesc)))
	})
	return file_ingestion_proto_rawDescData
}

var file_ingestion_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_ingestion_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_ingestion_proto_goTypes = []any{
	(Status)(0),                 // 0: ttdust.ingestion.v1.Status
	(SourceFormat)(0),           // 1: ttdust.ingestion.v1.SourceFormat
	(JobStatus)(0),              // 2: ttdust.ingestion.v1.JobStatus
	(*IngestRequest)(nil),       // 3: ttdust.ingestion.v1.IngestRequest
	(*IngestResponse)(nil),      // 4: ttdust.ingestion.v1.IngestResponse
	(*IngestBatchRequest)(nil),  // 5: ttdust.ingestion.v1.IngestBatchRequest
	(*IngestBatchResponse)(nil), // 6: ttdust.ingestion.v1.IngestBatchResponse
	(*BatchError)(nil),          // 7: ttdust.ingestion.v1.BatchError
	nil,                         // 8: ttdust.ingestion.v1.IngestRequest.MetadataEntry
	nil,                         // 9: ttdust.ingestion.v1.IngestBatchRequest.OptionsEntry
}
var file_ingestion_proto_depIdxs = []int32{
	8, // 0: ttdust.ingestion.v1.IngestRequest.metadata:type_name -> ttdust.ingestion.v1.IngestRequest.MetadataEntry
	0, // 1: ttdust.ingestion.v1.IngestResponse.status:type_name -> ttdust.ingestion.v1.Status
	1, // 2: ttdust.ingestion.v1.IngestBatchRequest.format:type_name -> ttdust.ingestion.v1.SourceFormat
	9, // 3: ttdust.ingestion.v1.IngestBatchRequest.options:type_name -> ttdust.ingestion.v1.IngestBatchRequest.OptionsEntry
	2, // 4: ttdust.ingestion.v1.IngestBatchResponse.status:type_name -> ttdust.ingestion.v1.JobStatus
	7, // 5: ttdust.ingestion.v1.IngestBatchResponse.errors:type_name -> ttdust.ingestion.v1.BatchError
	3, // 6: ttdust.ingestion.v1.IngestionService.IngestStream:input_type -> ttdust.ingestion.v1.IngestRequest
	5, // 7: ttdust.ingestion.v1.IngestionService.IngestBatch:input_type -> ttdust.ingestion.v1.IngestBatchRequest
	4, // 8: ttdust.ingestion.v1.IngestionService.IngestStream:output_type -> ttdust.ingestion.v1.IngestResponse
	6, // 9: ttdust.ingestion.v1.IngestionService.IngestBatch:output_type -> ttdust.ingestion.v1.IngestBatchResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_ingestion_proto_init() }
func file_ingestion_proto_init() {
	if File_ingestion_proto != nil {
		return
	}
	file_ingestion_proto_msgTypes[0].OneofWrappers = []any{}
	file_ingestion_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ingestion_proto_rawDesc), len(file_ingestion_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ingestion_proto_goTypes,
		DependencyIndexes: file_ingestion_proto_depIdxs,
		EnumInfos:         file_ingestion_proto_enumTypes,
		MessageInfos:      file_ingestion_proto_msgTypes,
	}.Build()
	File_ingestion_proto = out.File
	file_ingestion_proto_goTypes = nil
	file_ingestion_proto_depIdxs = nil
}
