// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: query.proto

package querypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Record struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	RecordId            string                 `protobuf:"bytes,1,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	StreamId            string                 `protobuf:"bytes,2,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	SequenceNumber      int64                  `protobuf:"varint,3,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	TimestampUnixMicros int64                  `protobuf:"varint,4,opt,name=timestamp_unix_micros,json=timestampUnixMicros,proto3" json:"timestamp_unix_micros,omitempty"`
	Payload             []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"` // JSON-encoded record
	Metadata            map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{0}
}

func (x *Record) GetRecordId() string {
	if x != nil {
		return x.RecordId
	}
	return ""
}

func (x *Record) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *Record) GetSequenceNumber() int64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *Record) GetTimestampUnixMicros() int64 {
	if x != nil {
		return x.TimestampUnixMicros
	}
	return 0
}

func (x *Record) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Record) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type QueryMetadata struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TotalRecordsScanned int64                  `protobuf:"varint,1,opt,name=total_records_scanned,json=totalRecordsScanned,proto3" json:"total_records_scanned,omitempty"`
	PartitionsScanned   int64                  `protobuf:"varint,2,opt,name=partitions_scanned,json=partitionsScanned,proto3" json:"partitions_scanned,omitempty"`
	CacheHits           int64                  `protobuf:"varint,3,opt,name=cache_hits,json=cacheHits,proto3" json:"cache_hits,omitempty"`
	ExecutionTimeMicros int64                  `protobuf:"varint,4,opt,name=execution_time_micros,json=executionTimeMicros,proto3" json:"execution_time_micros,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *QueryMetadata) Reset() {
	*x = QueryMetadata{}
	mi := &file_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryMetadata) ProtoMessage() {}

func (x *QueryMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryMetadata.ProtoReflect.Descriptor instead.
func (*QueryMetadata) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{1}
}

func (x *QueryMetadata) GetTotalRecordsScanned() int64 {
	if x != nil {
		return x.TotalRecordsScanned
	}
	return 0
}

func (x *QueryMetadata) GetPartitionsScanned() int64 {
	if x != nil {
		return x.PartitionsScanned
	}
	return 0
}

func (x *QueryMetadata) GetCacheHits() int64 {
	if x != nil {
		return x.CacheHits
	}
	return 0
}

func (x *QueryMetadata) GetExecutionTimeMicros() int64 {
	if x != nil {
		return x.ExecutionTimeMicros
	}
	return 0
}

type TimeRangeQueryRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	StreamId            string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	StartTimeUnixMicros int64                  `protobuf:"varint,2,opt,name=start_time_unix_micros,json=startTimeUnixMicros,proto3" json:"start_time_unix_micros,omitempty"`
	EndTimeUnixMicros   int64                  `protobuf:"varint,3,opt,name=end_time_unix_micros,json=endTimeUnixMicros,proto3" json:"end_time_unix_micros,omitempty"`
	Limit               *int32                 `protobuf:"varint,4,opt,name=limit,proto3,oneof" json:"limit,omitempty"`  // Max records (default 1000)
	Cursor              *string                `protobuf:"bytes,5,opt,name=cursor,proto3,oneof" json:"cursor,omitempty"` // Pagination cursor
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TimeRangeQueryRequest) Reset() {
	*x = TimeRangeQueryRequest{}
	mi := &file_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeRangeQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeRangeQueryRequest) ProtoMessage() {}

func (x *TimeRangeQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeRangeQueryRequest.ProtoReflect.Descriptor instead.
func (*TimeRangeQueryRequest) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{2}
}

func (x *TimeRangeQueryRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *TimeRangeQueryRequest) GetStartTimeUnixMicros() int64 {
	if x != nil {
		return x.StartTimeUnixMicros
	}
	return 0
}

func (x *TimeRangeQueryRequest) GetEndTimeUnixMicros() int64 {
	if x != nil {
		return x.EndTimeUnixMicros
	}
	return 0
}

func (x *TimeRangeQueryRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *TimeRangeQueryRequest) GetCursor() string {
	if x != nil && x.Cursor != nil {
		return *x.Cursor
	}
	return ""
}

type TimeRangeQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*Record              `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	NextCursor    *string                `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3,oneof" json:"next_cursor,omitempty"` // For pagination
	Metadata      *QueryMetadata         `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeRangeQueryResponse) Reset() {
	*x = TimeRangeQueryResponse{}
	mi := &file_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeRangeQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeRangeQueryResponse) ProtoMessage() {}

func (x *TimeRangeQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeRangeQueryResponse.ProtoReflect.Descriptor instead.
func (*TimeRangeQueryResponse) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{3}
}

func (x *TimeRangeQueryResponse) GetRecords() []*Record {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *TimeRangeQueryResponse) GetNextCursor() string {
	if x != nil && x.NextCursor != nil {
		return *x.NextCursor
	}
	return ""
}

func (x *TimeRangeQueryResponse) GetMetadata() *QueryMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type KeyLookupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	KeyField      string                 `protobuf:"bytes,2,opt,name=key_field,json=keyField,proto3" json:"key_field,omitempty"` // Field to match
	KeyValue      string                 `protobuf:"bytes,3,opt,name=key_value,json=keyValue,proto3" json:"key_value,omitempty"` // Value to find
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyLookupRequest) Reset() {
	*x = KeyLookupRequest{}
	mi := &file_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyLookupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyLookupRequest) ProtoMessage() {}

func (x *KeyLookupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyLookupRequest.ProtoReflect.Descriptor instead.
func (*KeyLookupRequest) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{4}
}

func (x *KeyLookupRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *KeyLookupRequest) GetKeyField() string {
	if x != nil {
		return x.KeyField
	}
	return ""
}

func (x *KeyLookupRequest) GetKeyValue() string {
	if x != nil {
		return x.KeyValue
	}
	return ""
}

type KeyLookupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *Record                `protobuf:"bytes,1,opt,name=record,proto3,oneof" json:"record,omitempty"` // Latest record with key
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyLookupResponse) Reset() {
	*x = KeyLookupResponse{}
	mi := &file_query_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyLookupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyLookupResponse) ProtoMessage() {}

func (x *KeyLookupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyLookupResponse.ProtoReflect.Descriptor instead.
func (*KeyLookupResponse) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{5}
}

func (x *KeyLookupResponse) GetRecord() *Record {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *KeyLookupResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type StreamingReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	StartSequence *int64                 `protobuf:"varint,2,opt,name=start_sequence,json=startSequence,proto3,oneof" json:"start_sequence,omitempty"` // Start from sequence number
	StartTime     *int64                 `protobuf:"varint,3,opt,name=start_time,json=startTime,proto3,oneof" json:"start_time,omitempty"`             // Or start from timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamingReadRequest) Reset() {
	*x = StreamingReadRequest{}
	mi := &file_query_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamingReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamingReadRequest) ProtoMessage() {}

func (x *StreamingReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamingReadRequest.ProtoReflect.Descriptor instead.
func (*StreamingReadRequest) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{6}
}

func (x *StreamingReadRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *StreamingReadRequest) GetStartSequence() int64 {
	if x != nil && x.StartSequence != nil {
		return *x.StartSequence
	}
	return 0
}

func (x *StreamingReadRequest) GetStartTime() int64 {
	if x != nil && x.StartTime != nil {
		return *x.StartTime
	}
	return 0
}

// Server streaming response
type StreamingReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *Record                `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	IsHistorical  bool                   `protobuf:"varint,2,opt,name=is_historical,json=isHistorical,proto3" json:"is_historical,omitempty"` // False when caught up to live
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamingReadResponse) Reset() {
	*x = StreamingReadResponse{}
	mi := &file_query_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamingReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamingReadResponse) ProtoMessage() {}

func (x *StreamingReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamingReadResponse.ProtoReflect.Descriptor instead.
func (*StreamingReadResponse) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{7}
}

func (x *StreamingReadResponse) GetRecord() *Record {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *StreamingReadResponse) GetIsHistorical() bool {
	if x != nil {
		return x.IsHistorical
	}
	return false
}

var File_query_proto protoreflect.FileDescriptor

const file_query_proto_rawDesc = "" +
	"\n" +
	"\vquery.proto\x12\x0fttdust.query.v1\"\xb9\x02\n" +
	"\x06Record\x12\x1b\n" +
	"\trecord_id\x18\x01 \x01(\tR\brecordId\x12\x1b\n" +
	"\tstream_id\x18\x02 \x01(\tR\bstreamId\x12'\n" +
	"\x0fsequence_number\x18\x03 \x01(\x03R\x0esequenceNumber\x122\n" +
	"\x15timestamp_unix_micros\x18\x04 \x01(\x03R\x13timestampUnixMicros\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x12A\n" +
	"\bmetadata\x18\x06 \x03(\v2%.ttdust.query.v1.Record.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc5\x01\n" +
	"\rQueryMetadata\x122\n" +
	"\x15total_records_scanned\x18\x01 \x01(\x03R\x13totalRecordsScanned\x12-\n" +
	"\x12partitions_scanned\x18\x02 \x01(\x03R\x11partitionsScanned\x12\x1d\n" +
	"\n" +
	"cache_hits\x18\x03 \x01(\x03R\tcacheHits\x122\n" +
	"\x15execution_time_micros\x18\x04 \x01(\x03R\x13executionTimeMicros\"\xe7\x01\n" +
	"\x15TimeRangeQueryRequest\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x123\n" +
	"\x16start_time_unix_micros\x18\x02 \x01(\x03R\x13startTimeUnixMicros\x12/\n" +
	"\x14end_time_unix_micros\x18\x03 \x01(\x03R\x11endTimeUnixMicros\x12\x19\n" +
	"\x05limit\x18\x04 \x01(\x05H\x00R\x05limit\x88\x01\x01\x12\x1b\n" +
	"\x06cursor\x18\x05 \x01(\tH\x01R\x06cursor\x88\x01\x01B\b\n" +
	"\x06_limitB\t\n" +
	"\a_cursor\"\xbd\x01\n" +
	"\x16TimeRangeQueryResponse\x121\n" +
	"\arecords\x18\x01 \x03(\v2\x17.ttdust.query.v1.RecordR\arecords\x12$\n" +
	"\vnext_cursor\x18\x02 \x01(\tH\x00R\n" +
	"nextCursor\x88\x01\x01\x12:\n" +
	"\bmetadata\x18\x03 \x01(\v2\x1e.ttdust.query.v1.QueryMetadataR\bmetadataB\x0e\n" +
	"\f_next_cursor\"i\n" +
	"\x10KeyLookupRequest\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12\x1b\n" +
	"\tkey_field\x18\x02 \x01(\tR\bkeyField\x12\x1b\n" +
	"\tkey_value\x18\x03 \x01(\tR\bkeyValue\"j\n" +
	"\x11KeyLookupResponse\x124\n" +
	"\x06record\x18\x01 \x01(\v2\x17.ttdust.query.v1.RecordH\x00R\x06record\x88\x01\x01\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05foundB\t\n" +
	"\a_record\"\xa5\x01\n" +
	"\x14StreamingReadRequest\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12*\n" +
	"\x0estart_sequence\x18\x02 \x01(\x03H\x00R\rstartSequence\x88\x01\x01\x12\"\n" +
	"\n" +
	"start_time\x18\x03 \x01(\x03H\x01R\tstartTime\x88\x01\x01B\x11\n" +
	"\x0f_start_sequenceB\r\n" +
	"\v_start_time\"m\n" +
	"\x15StreamingReadResponse\x12/\n" +
	"\x06record\x18\x01 \x01(\v2\x17.ttdust.query.v1.RecordR\x06record\x12#\n" +
	"\ris_historical\x18\x02 \x01(\bR\fisHistorical2\xa9\x02\n" +
	"\fQueryService\x12a\n" +
	"\x0eQueryTimeRange\x12&.ttdust.query.v1.TimeRangeQueryRequest\x1a'.ttdust.query.v1.TimeRangeQueryResponse\x12T\n" +
	"\vLookupByKey\x12!.ttdust.query.v1.KeyLookupRequest\x1a\".ttdust.query.v1.KeyLookupResponse\x12`\n" +
	"\rStreamingRead\x12%.ttdust.query.v1.StreamingReadRequest\x1a&.ttdust.query.v1.StreamingReadResponse0\x01B$Z\"GoTTDust/internal/genproto/querypbb\x06proto3"

var (
	file_query_proto_rawDescOnce sync.Once
	file_query_proto_rawDescData []byte
)

func file_query_proto_rawDescGZIP() []byte {
	file_query_proto_rawDescOnce.Do(func() {
		file_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_query_proto_rawDesc), len(file_query_proto_rawDesc)))
	})
	return file_query_proto_rawDescData
}

var file_query_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_query_proto_goTypes = []any{
	(*Record)(nil),                 // 0: ttdust.query.v1.Record
	(*QueryMetadata)(nil),          // 1: ttdust.query.v1.QueryMetadata
	(*TimeRangeQueryRequest)(nil),  // 2: ttdust.query.v1.TimeRangeQueryRequest
	(*TimeRangeQueryResponse)(nil), // 3: ttdust.query.v1.TimeRangeQueryResponse
	(*KeyLookupRequest)(nil),       // 4: ttdust.query.v1.KeyLookupRequest
	(*KeyLookupResponse)(nil),      // 5: ttdust.query.v1.KeyLookupResponse
	(*StreamingReadRequest)(nil),   // 6: ttdust.query.v1.StreamingReadRequest
	(*StreamingReadResponse)(nil),  // 7: ttdust.query.v1.StreamingReadResponse
	nil,                            // 8: ttdust.query.v1.Record.MetadataEntry
}
var file_query_proto_depIdxs = []int32{
	8, // 0: ttdust.query.v1.Record.metadata:type_name -> ttdust.query.v1.Record.MetadataEntry
	0, // 1: ttdust.query.v1.TimeRangeQueryResponse.records:type_name -> ttdust.query.v1.Record
	1, // 2: ttdust.query.v1.TimeRangeQueryResponse.metadata:type_name -> ttdust.query.v1.QueryMetadata
	0, // 3: ttdust.query.v1.KeyLookupResponse.record:type_name -> ttdust.query.v1.Record
	0, // 4: ttdust.query.v1.StreamingReadResponse.record:type_name -> ttdust.query.v1.Record
	2, // 5: ttdust.query.v1.QueryService.QueryTimeRange:input_type -> ttdust.query.v1.TimeRangeQueryRequest
	4, // 6: ttdust.query.v1.QueryService.LookupByKey:input_type -> ttdust.query.v1.KeyLookupRequest
	6, // 7: ttdust.query.v1.QueryService.StreamingRead:input_type -> ttdust.query.v1.StreamingReadRequest
	3, // 8: ttdust.query.v1.QueryService.QueryTimeRange:output_type -> ttdust.query.v1.TimeRangeQueryResponse
	5, // 9: ttdust.query.v1.QueryService.LookupByKey:output_type -> ttdust.query.v1.KeyLookupResponse
	7, // 10: ttdust.query.v1.QueryService.StreamingRead:output_type -> ttdust.query.v1.StreamingReadResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_query_proto_init() }
func file_query_proto_init() {
	if File_query_proto != nil {
		return
	}
	file_query_proto_msgTypes[2].OneofWrappers = []any{}
	file_query_proto_msgTypes[3].OneofWrappers = []any{}
	file_query_proto_msgTypes[5].OneofWrappers = []any{}
	file_query_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_query_proto_rawDesc), len(file_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_query_proto_goTypes,
		DependencyIndexes: file_query_proto_depIdxs,
		MessageInfos:      file_query_proto_msgTypes,
	}.Build()
	File_query_proto = out.File
	file_query_proto_goTypes = nil
	file_query_proto_depIdxs = nil
}
