// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: query.proto

package querypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	QueryService_QueryTimeRange_FullMethodName = "/ttdust.query.v1.QueryService/QueryTimeRange"
	QueryService_LookupByKey_FullMethodName    = "/ttdust.query.v1.QueryService/LookupByKey"
	QueryService_StreamingRead_FullMethodName  = "/ttdust.query.v1.QueryService/StreamingRead"
)

// QueryServiceClient is the client API for QueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryServiceClient interface {
	// Time-range query with pagination
	QueryTimeRange(ctx context.Context, in *TimeRangeQueryRequest, opts ...grpc.CallOption) (*TimeRangeQueryResponse, error)
	// Key-based lookup
	LookupByKey(ctx context.Context, in *KeyLookupRequest, opts ...grpc.CallOption) (*KeyLookupResponse, error)
	// Streaming read (server streaming)
	StreamingRead(ctx context.Context, in *StreamingReadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamingReadResponse], error)
}

type queryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryServiceClient(cc grpc.ClientConnInterface) QueryServiceClient {
	return &queryServiceClient{cc}
}

func (c *queryServiceClient) QueryTimeRange(ctx context.Context, in *TimeRangeQueryRequest, opts ...grpc.CallOption) (*TimeRangeQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TimeRangeQueryResponse)
	err := c.cc.Invoke(ctx, QueryService_QueryTimeRange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryServiceClient) LookupByKey(ctx context.Context, in *KeyLookupRequest, opts ...grpc.CallOption) (*KeyLookupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KeyLookupResponse)
	err := c.cc.Invoke(ctx, QueryService_LookupByKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryServiceClient) StreamingRead(ctx context.Context, in *StreamingReadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamingReadResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &QueryService_ServiceDesc.Streams[0], QueryService_StreamingRead_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamingReadRequest, StreamingReadResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type QueryService_StreamingReadClient = grpc.ServerStreamingClient[StreamingReadResponse]

// QueryServiceServer is the server API for QueryService service.
// All implementations must embed UnimplementedQueryServiceServer
// for forward compatibility.
type QueryServiceServer interface {
	// Time-range query with pagination
	QueryTimeRange(context.Context, *TimeRangeQueryRequest) (*TimeRangeQueryResponse, error)
	// Key-based lookup
	LookupByKey(context.Context, *KeyLookupRequest) (*KeyLookupResponse, error)
	// Streaming read (server streaming)
	StreamingRead(*StreamingReadRequest, grpc.ServerStreamingServer[StreamingReadResponse]) error
	mustEmbedUnimplementedQueryServiceServer()
}

// UnimplementedQueryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQueryServiceServer struct{}

func (UnimplementedQueryServiceServer) QueryTimeRange(context.Context, *TimeRangeQueryRequest) (*TimeRangeQueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryTimeRange not implemented")
}
func (UnimplementedQueryServiceServer) LookupByKey(context.Context, *KeyLookupRequest) (*KeyLookupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LookupByKey not implemented")
}
func (UnimplementedQueryServiceServer) StreamingRead(*StreamingReadRequest, grpc.ServerStreamingServer[StreamingReadResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamingRead not implemented")
}
func (UnimplementedQueryServiceServer) mustEmbedUnimplementedQueryServiceServer() {}
func (UnimplementedQueryServiceServer) testEmbeddedByValue()                      {}

// UnsafeQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServiceServer will
// result in compilation errors.
type UnsafeQueryServiceServer interface {
	mustEmbedUnimplementedQueryServiceServer()
}

func RegisterQueryServiceServer(s grpc.ServiceRegistrar, srv QueryServiceServer) {
	// If the following call panics, it indicates UnimplementedQueryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&QueryService_ServiceDesc, srv)
}

func _QueryService_QueryTimeRange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TimeRangeQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).QueryTimeRange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueryService_QueryTimeRange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).QueryTimeRange(ctx, req.(*TimeRangeQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryService_LookupByKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyLookupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).LookupByKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueryService_LookupByKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).LookupByKey(ctx, req.(*KeyLookupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryService_StreamingRead_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamingReadRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(QueryServiceServer).StreamingRead(m, &grpc.GenericServerStream[StreamingReadRequest, StreamingReadResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type QueryService_StreamingReadServer = grpc.ServerStreamingServer[StreamingReadResponse]

// QueryService_ServiceDesc is the grpc.ServiceDesc for QueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ttdust.query.v1.QueryService",
	HandlerType: (*QueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryTimeRange",
			Handler:    _QueryService_QueryTimeRange_Handler,
		},
		{
			MethodName: "LookupByKey",
			Handler:    _QueryService_LookupByKey_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamingRead",
			Handler:       _QueryService_StreamingRead_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "query.proto",
}
