// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: admin.proto

package adminpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	SchemaId      string                 `protobuf:"bytes,4,opt,name=schema_id,json=schemaId,proto3" json:"schema_id,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Retention     *RetentionConfig       `protobuf:"bytes,6,opt,name=retention,proto3" json:"retention,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamConfig) Reset() {
	*x = StreamConfig{}
	mi := &file_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamConfig) ProtoMessage() {}

func (x *StreamConfig) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamConfig.ProtoReflect.Descriptor instead.
func (*StreamConfig) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{0}
}

func (x *StreamConfig) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *StreamConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StreamConfig) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *StreamConfig) GetSchemaId() string {
	if x != nil {
		return x.SchemaId
	}
	return ""
}

func (x *StreamConfig) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *StreamConfig) GetRetention() *RetentionConfig {
	if x != nil {
		return x.Retention
	}
	return nil
}

type RetentionConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RetentionDays int64                  `protobuf:"varint,1,opt,name=retention_days,json=retentionDays,proto3" json:"retention_days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetentionConfig) Reset() {
	*x = RetentionConfig{}
	mi := &file_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetentionConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetentionConfig) ProtoMessage() {}

func (x *RetentionConfig) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetentionConfig.ProtoReflect.Descriptor instead.
func (*RetentionConfig) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{1}
}

func (x *RetentionConfig) GetRetentionDays() int64 {
	if x != nil {
		return x.RetentionDays
	}
	return 0
}

type CreateStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *StreamConfig          `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStreamRequest) Reset() {
	*x = CreateStreamRequest{}
	mi := &file_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStreamRequest) ProtoMessage() {}

func (x *CreateStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStreamRequest.ProtoReflect.Descriptor instead.
func (*CreateStreamRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{2}
}

func (x *CreateStreamRequest) GetConfig() *StreamConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type CreateStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stream        *StreamConfig          `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStreamResponse) Reset() {
	*x = CreateStreamResponse{}
	mi := &file_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStreamResponse) ProtoMessage() {}

func (x *CreateStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStreamResponse.ProtoReflect.Descriptor instead.
func (*CreateStreamResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{3}
}

func (x *CreateStreamResponse) GetStream() *StreamConfig {
	if x != nil {
		return x.Stream
	}
	return nil
}

type UpdateStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *StreamConfig          `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStreamRequest) Reset() {
	*x = UpdateStreamRequest{}
	mi := &file_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStreamRequest) ProtoMessage() {}

func (x *UpdateStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStreamRequest.ProtoReflect.Descriptor instead.
func (*UpdateStreamRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateStreamRequest) GetConfig() *StreamConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type UpdateStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stream        *StreamConfig          `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStreamResponse) Reset() {
	*x = UpdateStreamResponse{}
	mi := &file_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStreamResponse) ProtoMessage() {}

func (x *UpdateStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStreamResponse.ProtoReflect.Descriptor instead.
func (*UpdateStreamResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateStreamResponse) GetStream() *StreamConfig {
	if x != nil {
		return x.Stream
	}
	return nil
}

type DeleteStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"` // Must purge data first unless force=true
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStreamRequest) Reset() {
	*x = DeleteStreamRequest{}
	mi := &file_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStreamRequest) ProtoMessage() {}

func (x *DeleteStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStreamRequest.ProtoReflect.Descriptor instead.
func (*DeleteStreamRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteStreamRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *DeleteStreamRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type DeleteStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStreamResponse) Reset() {
	*x = DeleteStreamResponse{}
	mi := &file_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStreamResponse) ProtoMessage() {}

func (x *DeleteStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStreamResponse.ProtoReflect.Descriptor instead.
func (*DeleteStreamResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteStreamResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListStreamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         *int32                 `protobuf:"varint,1,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Cursor        *string                `protobuf:"bytes,2,opt,name=cursor,proto3,oneof" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStreamsRequest) Reset() {
	*x = ListStreamsRequest{}
	mi := &file_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStreamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStreamsRequest) ProtoMessage() {}

func (x *ListStreamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStreamsRequest.ProtoReflect.Descriptor instead.
func (*ListStreamsRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{8}
}

func (x *ListStreamsRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *ListStreamsRequest) GetCursor() string {
	if x != nil && x.Cursor != nil {
		return *x.Cursor
	}
	return ""
}

type ListStreamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Streams       []*StreamConfig        `protobuf:"bytes,1,rep,name=streams,proto3" json:"streams,omitempty"`
	NextCursor    *string                `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3,oneof" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStreamsResponse) Reset() {
	*x = ListStreamsResponse{}
	mi := &file_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStreamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStreamsResponse) ProtoMessage() {}

func (x *ListStreamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStreamsResponse.ProtoReflect.Descriptor instead.
func (*ListStreamsResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{9}
}

func (x *ListStreamsResponse) GetStreams() []*StreamConfig {
	if x != nil {
		return x.Streams
	}
	return nil
}

func (x *ListStreamsResponse) GetNextCursor() string {
	if x != nil && x.NextCursor != nil {
		return *x.NextCursor
	}
	return ""
}

type GetStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStreamRequest) Reset() {
	*x = GetStreamRequest{}
	mi := &file_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStreamRequest) ProtoMessage() {}

func (x *GetStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStreamRequest.ProtoReflect.Descriptor instead.
func (*GetStreamRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{10}
}

func (x *GetStreamRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

type GetStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stream        *StreamConfig          `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStreamResponse) Reset() {
	*x = GetStreamResponse{}
	mi := &file_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStreamResponse) ProtoMessage() {}

func (x *GetStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStreamResponse.ProtoReflect.Descriptor instead.
func (*GetStreamResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{11}
}

func (x *GetStreamResponse) GetStream() *StreamConfig {
	if x != nil {
		return x.Stream
	}
	return nil
}

var File_admin_proto protoreflect.FileDescriptor

const file_admin_proto_rawDesc = "" +
	"\n" +
	"\vadmin.proto\x12\x0fttdust.admin.v1\"\xbc\x02\n" +
	"\fStreamConfig\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tschema_id\x18\x04 \x01(\tR\bschemaId\x12A\n" +
	"\x06labels\x18\x05 \x03(\v2).ttdust.admin.v1.StreamConfig.LabelsEntryR\x06labels\x12>\n" +
	"\tretention\x18\x06 \x01(\v2 .ttdust.admin.v1.RetentionConfigR\tretention\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"8\n" +
	"\x0fRetentionConfig\x12%\n" +
	"\x0eretention_days\x18\x01 \x01(\x03R\rretentionDays\"L\n" +
	"\x13CreateStreamRequest\x125\n" +
	"\x06config\x18\x01 \x01(\v2\x1d.ttdust.admin.v1.StreamConfigR\x06config\"M\n" +
	"\x14CreateStreamResponse\x125\n" +
	"\x06stream\x18\x01 \x01(\v2\x1d.ttdust.admin.v1.StreamConfigR\x06stream\"L\n" +
	"\x13UpdateStreamRequest\x125\n" +
	"\x06config\x18\x01 \x01(\v2\x1d.ttdust.admin.v1.StreamConfigR\x06config\"M\n" +
	"\x14UpdateStreamResponse\x125\n" +
	"\x06stream\x18\x01 \x01(\v2\x1d.ttdust.admin.v1.StreamConfigR\x06stream\"H\n" +
	"\x13DeleteStreamRequest\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"0\n" +
	"\x14DeleteStreamResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"a\n" +
	"\x12ListStreamsRequest\x12\x19\n" +
	"\x05limit\x18\x01 \x01(\x05H\x00R\x05limit\x88\x01\x01\x12\x1b\n" +
	"\x06cursor\x18\x02 \x01(\tH\x01R\x06cursor\x88\x01\x01B\b\n" +
	"\x06_limitB\t\n" +
	"\a_cursor\"\x84\x01\n" +
	"\x13ListStreamsResponse\x127\n" +
	"\astreams\x18\x01 \x03(\v2\x1d.ttdust.admin.v1.StreamConfigR\astreams\x12$\n" +
	"\vnext_cursor\x18\x02 \x01(\tH\x00R\n" +
	"nextCursor\x88\x01\x01B\x0e\n" +
	"\f_next_cursor\"/\n" +
	"\x10GetStreamRequest\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\"J\n" +
	"\x11GetStreamResponse\x125\n" +
	"\x06stream\x18\x01 \x01(\v2\x1d.ttdust.admin.v1.StreamConfigR\x06stream2\xd3\x03\n" +
	"\fAdminService\x12[\n" +
	"\fCreateStream\x12$.ttdust.admin.v1.CreateStreamRequest\x1a%.ttdust.admin.v1.CreateStreamResponse\x12[\n" +
	"\fUpdateStream\x12$.ttdust.admin.v1.UpdateStreamRequest\x1a%.ttdust.admin.v1.UpdateStreamResponse\x12[\n" +
	"\fDeleteStream\x12$.ttdust.admin.v1.DeleteStreamRequest\x1a%.ttdust.admin.v1.DeleteStreamResponse\x12X\n" +
	"\vListStreams\x12#.ttdust.admin.v1.ListStreamsRequest\x1a$.ttdust.admin.v1.ListStreamsResponse\x12R\n" +
	"\tGetStream\x12!.ttdust.admin.v1.GetStreamRequest\x1a\".ttdust.admin.v1.GetStreamResponseB$Z\"GoTTDust/internal/genproto/adminpbb\x06proto3"

var (
	file_admin_proto_rawDescOnce sync.Once
	file_admin_proto_rawDescData []byte
)

func file_admin_proto_rawDescGZIP() []byte {
	file_admin_proto_rawDescOnce.Do(func() {
		file_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_proto_rawDesc), len(file_admin_proto_rawDesc)))
	})
	return file_admin_proto_rawDescData
}

var file_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_admin_proto_goTypes = []any{
	(*StreamConfig)(nil),         // 0: ttdust.admin.v1.StreamConfig
	(*RetentionConfig)(nil),      // 1: ttdust.admin.v1.RetentionConfig
	(*CreateStreamRequest)(nil),  // 2: ttdust.admin.v1.CreateStreamRequest
	(*CreateStreamResponse)(nil), // 3: ttdust.admin.v1.CreateStreamResponse
	(*UpdateStreamRequest)(nil),  // 4: ttdust.admin.v1.UpdateStreamRequest
	(*UpdateStreamResponse)(nil), // 5: ttdust.admin.v1.UpdateStreamResponse
	(*DeleteStreamRequest)(nil),  // 6: ttdust.admin.v1.DeleteStreamRequest
	(*DeleteStreamResponse)(nil), // 7: ttdust.admin.v1.DeleteStreamResponse
	(*ListStreamsRequest)(nil),   // 8: ttdust.admin.v1.ListStreamsRequest
	(*ListStreamsResponse)(nil),  // 9: ttdust.admin.v1.ListStreamsResponse
	(*GetStreamRequest)(nil),     // 10: ttdust.admin.v1.GetStreamRequest
	(*GetStreamResponse)(nil),    // 11: ttdust.admin.v1.GetStreamResponse
	nil,                          // 12: ttdust.admin.v1.StreamConfig.LabelsEntry
}
var file_admin_proto_depIdxs = []int32{
	12, // 0: ttdust.admin.v1.StreamConfig.labels:type_name -> ttdust.admin.v1.StreamConfig.LabelsEntry
	1,  // 1: ttdust.admin.v1.StreamConfig.retention:type_name -> ttdust.admin.v1.RetentionConfig
	0,  // 2: ttdust.admin.v1.CreateStreamRequest.config:type_name -> ttdust.admin.v1.StreamConfig
	0,  // 3: ttdust.admin.v1.CreateStreamResponse.stream:type_name -> ttdust.admin.v1.StreamConfig
	0,  // 4: ttdust.admin.v1.UpdateStreamRequest.config:type_name -> ttdust.admin.v1.StreamConfig
	0,  // 5: ttdust.admin.v1.UpdateStreamResponse.stream:type_name -> ttdust.admin.v1.StreamConfig
	0,  // 6: ttdust.admin.v1.ListStreamsResponse.streams:type_name -> ttdust.admin.v1.StreamConfig
	0,  // 7: ttdust.admin.v1.GetStreamResponse.stream:type_name -> ttdust.admin.v1.StreamConfig
	2,  // 8: ttdust.admin.v1.AdminService.CreateStream:input_type -> ttdust.admin.v1.CreateStreamRequest
	4,  // 9: ttdust.admin.v1.AdminService.UpdateStream:input_type -> ttdust.admin.v1.UpdateStreamRequest
	6,  // 10: ttdust.admin.v1.AdminService.DeleteStream:input_type -> ttdust.admin.v1.DeleteStreamRequest
	8,  // 11: ttdust.admin.v1.AdminService.ListStreams:input_type -> ttdust.admin.v1.ListStreamsRequest
	10, // 12: ttdust.admin.v1.AdminService.GetStream:input_type -> ttdust.admin.v1.GetStreamRequest
	3,  // 13: ttdust.admin.v1.AdminService.CreateStream:output_type -> ttdust.admin.v1.CreateStreamResponse
	5,  // 14: ttdust.admin.v1.AdminService.UpdateStream:output_type -> ttdust.admin.v1.UpdateStreamResponse
	7,  // 15: ttdust.admin.v1.AdminService.DeleteStream:output_type -> ttdust.admin.v1.DeleteStreamResponse
	9,  // 16: ttdust.admin.v1.AdminService.ListStreams:output_type -> ttdust.admin.v1.ListStreamsResponse
	11, // 17: ttdust.admin.v1.AdminService.GetStream:output_type -> ttdust.admin.v1.GetStreamResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_admin_proto_init() }
func file_admin_proto_init() {
	if File_admin_proto != nil {
		return
	}
	file_admin_proto_msgTypes[8].OneofWrappers = []any{}
	file_admin_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_proto_rawDesc), len(file_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_proto_goTypes,
		DependencyIndexes: file_admin_proto_depIdxs,
		MessageInfos:      file_admin_proto_msgTypes,
	}.Build()
	File_admin_proto = out.File
	file_admin_proto_goTypes = nil
	file_admin_proto_depIdxs = nil
}
